version: '3.7'
services:
  client:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
